/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as QuemSouRouteImport } from './routes/quem-sou'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDiagnosticoRouteImport } from './routes/admin.diagnostico'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminMidiaRouteImport } from './routes/admin.midia'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as ApiEventoRouteImport } from './routes/api.evento'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as LivrosIndexRouteImport } from './routes/livros.index'
import { Route as LivrosSlugRouteImport } from './routes/livros.$slug'
import { Route as MentoriasIndexRouteImport } from './routes/mentorias.index'
import { Route as MentoriasSlugRouteImport } from './routes/mentorias.$slug'
import { Route as TreinamentosIndexRouteImport } from './routes/treinamentos.index'
import { Route as TreinamentosSlugRouteImport } from './routes/treinamentos.$slug'
import { Route as AdminConteudoIndexRouteImport } from './routes/admin.conteudo.index'
import { Route as AdminPaginasIndexRouteImport } from './routes/admin.paginas.index'
import { Route as AdminPaginasChaveRouteImport } from './routes/admin.paginas.$chave'
import { Route as AdminConteudoColecaoIndexRouteImport } from './routes/admin.conteudo.$colecao.index'
import { Route as AdminConteudoColecaoIdRouteImport } from './routes/admin.conteudo.$colecao.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSouRoute = QuemSouRouteImport.update({
  id: '/quem-sou',
  path: '/quem-sou',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticoRoute = AdminDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiaRoute = AdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEventoRoute = ApiEventoRouteImport.update({
  id: '/api/evento',
  path: '/api/evento',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosIndexRoute = LivrosIndexRouteImport.update({
  id: '/livros/',
  path: '/livros/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosSlugRoute = LivrosSlugRouteImport.update({
  id: '/livros/$slug',
  path: '/livros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasIndexRoute = MentoriasIndexRouteImport.update({
  id: '/mentorias/',
  path: '/mentorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasSlugRoute = MentoriasSlugRouteImport.update({
  id: '/mentorias/$slug',
  path: '/mentorias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosIndexRoute = TreinamentosIndexRouteImport.update({
  id: '/treinamentos/',
  path: '/treinamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosSlugRoute = TreinamentosSlugRouteImport.update({
  id: '/treinamentos/$slug',
  path: '/treinamentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudoIndexRoute = AdminConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasIndexRoute = AdminPaginasIndexRouteImport.update({
  id: '/paginas/',
  path: '/paginas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasChaveRoute = AdminPaginasChaveRouteImport.update({
  id: '/paginas/$chave',
  path: '/paginas/$chave',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoColecaoIndexRoute =
  AdminConteudoColecaoIndexRouteImport.update({
    id: '/conteudo/$colecao/',
    path: '/conteudo/$colecao/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConteudoColecaoIdRoute = AdminConteudoColecaoIdRouteImport.update({
  id: '/conteudo/$colecao/$id',
  path: '/conteudo/$colecao/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/entrar': typeof EntrarRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-sou': typeof QuemSouRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/evento': typeof ApiEventoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/livros/$slug': typeof LivrosSlugRoute
  '/mentorias/$slug': typeof MentoriasSlugRoute
  '/treinamentos/$slug': typeof TreinamentosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/mentorias/': typeof MentoriasIndexRoute
  '/treinamentos/': typeof TreinamentosIndexRoute
  '/admin/paginas/$chave': typeof AdminPaginasChaveRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/paginas/': typeof AdminPaginasIndexRoute
  '/admin/conteudo/$colecao/$id': typeof AdminConteudoColecaoIdRoute
  '/admin/conteudo/$colecao/': typeof AdminConteudoColecaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/entrar': typeof EntrarRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-sou': typeof QuemSouRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/evento': typeof ApiEventoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/livros/$slug': typeof LivrosSlugRoute
  '/mentorias/$slug': typeof MentoriasSlugRoute
  '/treinamentos/$slug': typeof TreinamentosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/livros': typeof LivrosIndexRoute
  '/mentorias': typeof MentoriasIndexRoute
  '/treinamentos': typeof TreinamentosIndexRoute
  '/admin/paginas/$chave': typeof AdminPaginasChaveRoute
  '/admin/conteudo': typeof AdminConteudoIndexRoute
  '/admin/paginas': typeof AdminPaginasIndexRoute
  '/admin/conteudo/$colecao/$id': typeof AdminConteudoColecaoIdRoute
  '/admin/conteudo/$colecao': typeof AdminConteudoColecaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/entrar': typeof EntrarRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-sou': typeof QuemSouRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/evento': typeof ApiEventoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/livros/$slug': typeof LivrosSlugRoute
  '/mentorias/$slug': typeof MentoriasSlugRoute
  '/treinamentos/$slug': typeof TreinamentosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/mentorias/': typeof MentoriasIndexRoute
  '/treinamentos/': typeof TreinamentosIndexRoute
  '/admin/paginas/$chave': typeof AdminPaginasChaveRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/paginas/': typeof AdminPaginasIndexRoute
  '/admin/conteudo/$colecao/$id': typeof AdminConteudoColecaoIdRoute
  '/admin/conteudo/$colecao/': typeof AdminConteudoColecaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/depoimentos'
    | '/diagnostico'
    | '/entrar'
    | '/metodo'
    | '/privacidade'
    | '/quem-sou'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/admin/diagnostico'
    | '/admin/leads'
    | '/admin/midia'
    | '/admin/usuarios'
    | '/api/evento'
    | '/blog/$slug'
    | '/cursos/$slug'
    | '/livros/$slug'
    | '/mentorias/$slug'
    | '/treinamentos/$slug'
    | '/admin/'
    | '/blog/'
    | '/cursos/'
    | '/livros/'
    | '/mentorias/'
    | '/treinamentos/'
    | '/admin/paginas/$chave'
    | '/admin/conteudo/'
    | '/admin/paginas/'
    | '/admin/conteudo/$colecao/$id'
    | '/admin/conteudo/$colecao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/depoimentos'
    | '/diagnostico'
    | '/entrar'
    | '/metodo'
    | '/privacidade'
    | '/quem-sou'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/admin/diagnostico'
    | '/admin/leads'
    | '/admin/midia'
    | '/admin/usuarios'
    | '/api/evento'
    | '/blog/$slug'
    | '/cursos/$slug'
    | '/livros/$slug'
    | '/mentorias/$slug'
    | '/treinamentos/$slug'
    | '/admin'
    | '/blog'
    | '/cursos'
    | '/livros'
    | '/mentorias'
    | '/treinamentos'
    | '/admin/paginas/$chave'
    | '/admin/conteudo'
    | '/admin/paginas'
    | '/admin/conteudo/$colecao/$id'
    | '/admin/conteudo/$colecao'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/depoimentos'
    | '/diagnostico'
    | '/entrar'
    | '/metodo'
    | '/privacidade'
    | '/quem-sou'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/admin/diagnostico'
    | '/admin/leads'
    | '/admin/midia'
    | '/admin/usuarios'
    | '/api/evento'
    | '/blog/$slug'
    | '/cursos/$slug'
    | '/livros/$slug'
    | '/mentorias/$slug'
    | '/treinamentos/$slug'
    | '/admin/'
    | '/blog/'
    | '/cursos/'
    | '/livros/'
    | '/mentorias/'
    | '/treinamentos/'
    | '/admin/paginas/$chave'
    | '/admin/conteudo/'
    | '/admin/paginas/'
    | '/admin/conteudo/$colecao/$id'
    | '/admin/conteudo/$colecao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EntrarRoute: typeof EntrarRoute
  MetodoRoute: typeof MetodoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QuemSouRoute: typeof QuemSouRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEventoRoute: typeof ApiEventoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CursosSlugRoute: typeof CursosSlugRoute
  LivrosSlugRoute: typeof LivrosSlugRoute
  MentoriasSlugRoute: typeof MentoriasSlugRoute
  TreinamentosSlugRoute: typeof TreinamentosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CursosIndexRoute: typeof CursosIndexRoute
  LivrosIndexRoute: typeof LivrosIndexRoute
  MentoriasIndexRoute: typeof MentoriasIndexRoute
  TreinamentosIndexRoute: typeof TreinamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-sou': {
      id: '/quem-sou'
      path: '/quem-sou'
      fullPath: '/quem-sou'
      preLoaderRoute: typeof QuemSouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostico': {
      id: '/admin/diagnostico'
      path: '/diagnostico'
      fullPath: '/admin/diagnostico'
      preLoaderRoute: typeof AdminDiagnosticoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midia': {
      id: '/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminMidiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/evento': {
      id: '/api/evento'
      path: '/api/evento'
      fullPath: '/api/evento'
      preLoaderRoute: typeof ApiEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/': {
      id: '/livros/'
      path: '/livros'
      fullPath: '/livros/'
      preLoaderRoute: typeof LivrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/$slug': {
      id: '/livros/$slug'
      path: '/livros/$slug'
      fullPath: '/livros/$slug'
      preLoaderRoute: typeof LivrosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias/': {
      id: '/mentorias/'
      path: '/mentorias'
      fullPath: '/mentorias/'
      preLoaderRoute: typeof MentoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias/$slug': {
      id: '/mentorias/$slug'
      path: '/mentorias/$slug'
      fullPath: '/mentorias/$slug'
      preLoaderRoute: typeof MentoriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos/': {
      id: '/treinamentos/'
      path: '/treinamentos'
      fullPath: '/treinamentos/'
      preLoaderRoute: typeof TreinamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos/$slug': {
      id: '/treinamentos/$slug'
      path: '/treinamentos/$slug'
      fullPath: '/treinamentos/$slug'
      preLoaderRoute: typeof TreinamentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudo/': {
      id: '/admin/conteudo/'
      path: '/conteudo'
      fullPath: '/admin/conteudo/'
      preLoaderRoute: typeof AdminConteudoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas/': {
      id: '/admin/paginas/'
      path: '/paginas'
      fullPath: '/admin/paginas/'
      preLoaderRoute: typeof AdminPaginasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas/$chave': {
      id: '/admin/paginas/$chave'
      path: '/paginas/$chave'
      fullPath: '/admin/paginas/$chave'
      preLoaderRoute: typeof AdminPaginasChaveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/$colecao/': {
      id: '/admin/conteudo/$colecao/'
      path: '/conteudo/$colecao'
      fullPath: '/admin/conteudo/$colecao/'
      preLoaderRoute: typeof AdminConteudoColecaoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/$colecao/$id': {
      id: '/admin/conteudo/$colecao/$id'
      path: '/conteudo/$colecao/$id'
      fullPath: '/admin/conteudo/$colecao/$id'
      preLoaderRoute: typeof AdminConteudoColecaoIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDiagnosticoRoute: typeof AdminDiagnosticoRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMidiaRoute: typeof AdminMidiaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPaginasChaveRoute: typeof AdminPaginasChaveRoute
  AdminConteudoIndexRoute: typeof AdminConteudoIndexRoute
  AdminPaginasIndexRoute: typeof AdminPaginasIndexRoute
  AdminConteudoColecaoIdRoute: typeof AdminConteudoColecaoIdRoute
  AdminConteudoColecaoIndexRoute: typeof AdminConteudoColecaoIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDiagnosticoRoute: AdminDiagnosticoRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMidiaRoute: AdminMidiaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPaginasChaveRoute: AdminPaginasChaveRoute,
  AdminConteudoIndexRoute: AdminConteudoIndexRoute,
  AdminPaginasIndexRoute: AdminPaginasIndexRoute,
  AdminConteudoColecaoIdRoute: AdminConteudoColecaoIdRoute,
  AdminConteudoColecaoIndexRoute: AdminConteudoColecaoIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EntrarRoute: EntrarRoute,
  MetodoRoute: MetodoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QuemSouRoute: QuemSouRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEventoRoute: ApiEventoRoute,
  BlogSlugRoute: BlogSlugRoute,
  CursosSlugRoute: CursosSlugRoute,
  LivrosSlugRoute: LivrosSlugRoute,
  MentoriasSlugRoute: MentoriasSlugRoute,
  TreinamentosSlugRoute: TreinamentosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CursosIndexRoute: CursosIndexRoute,
  LivrosIndexRoute: LivrosIndexRoute,
  MentoriasIndexRoute: MentoriasIndexRoute,
  TreinamentosIndexRoute: TreinamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
